Added code for pruning based on edgeLeakID
note that this code should accurately account for the "prunable" index with one
exception: in principle, if a species was never included in one of edgeID or
edgeLeakID due to the fact that not all the reactants leading to this species
were in the core, it would be possible for the species to be incorrectly pruned