Some error messages are converted to warnings.
ERROR: Could not find a polycyclic ring strain correction.  --> warning
ERROR: Thermochemistry of polycyclic species does not contain
corrections for thepolyclic ring system. It is advised to review the
thermochemistry data of this species. --> warning
ERROR: Error in database --> warning