an attempted fix for mm4 error (see below)
java.io.IOException: Cannot run program "QMfiles//LVZWSLJZHVFIQJ-UHFFFAOYAL.com" (in directory "QMfiles"): java.io.IOException: error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:459)
        at java.lang.Runtime.exec(Runtime.java:593)
        at java.lang.Runtime.exec(Runtime.java:431)
        at jing.chem.QMTP.runMM4(QMTP.java:884)
        at jing.chem.QMTP.generateQMThermoData(QMTP.java:330)
        at jing.chem.QMTP.generateThermoData(QMTP.java:213)
        at jing.chem.ChemGraph.generateThermoData(ChemGraph.java:1165)
        at jing.chem.ChemGraph.getThermoData(ChemGraph.java:1685)
        at jing.chem.Species.findStablestThermoData(Species.java:338)
        at jing.chem.Species.<init>(Species.java:118)
        at jing.chem.Species.make(Species.java:872)
        at jing.rxnSys.ReactionModelGenerator.populateInitialStatusListWithReactiveSpecies(ReactionModelGenerator.java:4789)
        at jing.rxnSys.ReactionModelGenerator.initializeReactionSystems(ReactionModelGenerator.java:504)
        at jing.rxnSys.ReactionModelGenerator.modelGeneration(ReactionModelGenerator.java:1244)
        at RMG.main(RMG.java:57)
Caused by: java.io.IOException: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:148)
        at java.lang.ProcessImpl.start(ProcessImpl.java:65)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)
        ... 14 more